queries = [
`SELECT
	TO_CHAR("ISSUED_DATE"::timestamp, 'YYYY') AS YEAR,
	COUNT(*) PERMITS,
	COUNT(DISTINCT "Parcel_ID") PROPERTIES,
	SUM("DECLARED_VALUATION"::decimal) TOTAL_VALUE
FROM "6ddcd912-32a0-43df-9908-63574f8c7e77"
WHERE
	"ZIP" = '02128'
	AND "ADDRESS" NOT ILIKE '%%Harborside%%'
	AND "ADDRESS" NOT ILIKE '%%Logan%%'
	AND "ADDRESS" NOT ILIKE '%%Terminal%%'
	AND "DECLARED_VALUATION"::decimal < 500000
GROUP BY TO_CHAR("ISSUED_DATE"::timestamp, 'YYYY')
ORDER BY TO_CHAR("ISSUED_DATE"::timestamp, 'YYYY') ASC`,
`SELECT
	*
FROM "6ddcd912-32a0-43df-9908-63574f8c7e77"
LIMIT 1`
]